### ISSUE TITLE
Readme discrepancies

### ISSUE THREAD

**Issue by spvickers** [IMSGlobal/caliper-php-public#3]
I think the readme file for this repository is out-of-date.  It says to add the following line to your application:

`require_once '/path/to/caliper-php/lib/CaliperSensor.php';`

but this file does not exist.  It also appears to use static methods of the Caliper class which does not exist.  The example app instantiates an instance of the Sensor class which is what I assume the Readme file should suggest.

I also note that the class files are not namespaced; is there a reason for this?  I think this may make it difficult to integrate with some applications and runs the risk of class name clashes.

**Comment by lsloan** [comment]
This was eventually resolved by IMSGlobal/caliper-php#149.
